services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend
  express:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      ADMIN_EMAIL: /run/secrets/admin_email
      ADMIN_PASSWORD: /run/secrets/admin_password
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - backend
      - frontend
    image: asutton/buzzmydayexpressapi:1.0
    secrets:
      - admin_email
      - admin_password
  
  client:
    build:
      context: ./coffee_front_end
    container_name: react-frontend
    ports:
      - "5173:80"
    networks:
      - frontend
    depends_on:
      - express
    image: asutton/buzzmydayreactapp:1.0
volumes:
  mongo-data:
    driver: local
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
secrets:
  admin_email:
    file: .secrets/admin_email
  admin_password:
    file: .secrets/admin_password




