name: Deploy to Netlify and render

on:
  push:
    branches:
      - main

jobs:
  build-deploy-frontend:
    name: build frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./coffee_front_end

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      
      - name: Install Dependencies
        run: npm install
        
      - name: Run tests
        run: npm run test --if-present
      
      - name: Build the frontend
        run: npm run build

      - name: List dist contents
        run: ls -la ./dist

      - name: Netlify Actions
        uses: nwtgck/actions-netlify@v3.0.0
        with:
          publish-dir: './dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_PROJECT_ID: ${{ secrets.NETLIFY_PROJECT_ID }}
        timeout-minutes: 1
    
  deploy-render:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./coffee_front_end
        permissions:
          deployments: write

        steps:
          - uses: JorgeLNJunior/render-deploy@v1.4.5
            with:
                service_id: ${{ secrets.RENDER_SERVICE_ID }}
                api_key: ${{ secrets.RENDER_API_KEY }}
                clear_cache: true # Optional: Clear Render's build cache
                wait_deploy: true
                github_deployment: true
                deployment_environment: 'production'
                github_token: ${{ secrets.GITHUB_TOKEN }}
            timeout-minutes: 1
  

      

        