name: Tag and Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Github Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Bump version and tag commit
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GH_TOKEN }}

      - name: GitHub Release
        uses: elgohr/Github-Release-Action@release-20241111151247
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          title: New Release
          tag: $${{ steps.tag.outputs.new_tag }}
          



